# Default configuration for ensembled inference.

defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

inference:
  # Inference arguments
  weights_path: model_weights/
  model_names:
    - pippack_model_1
    - pippack_model_2
    - pippack_model_3
  pdb_path: pdb/6qi7/
  output_dir: pdb/6qi7/repack_ensembled/
  n_recycle: 3
  temperature: 0.0
  replace_seqs: True
  use_resample: True
  force_cpu: False
  batch_size: 10000
  seed: 42

  # Debugging
  debug: False

  resample_args:
    sample_temp: 0.5
    clash_overlap_tolerance: 0.6
    pro_tolerance_factor: 12
    max_iters: 10
    metropolis_temp: 0.000005

hydra:
  run:
    dir: .
  output_subdir: null